const express=require('express')
const router=express.Router();
const UserController=require('../Controller/userController')
router.get('/items/:location',UserController.items)
router.post('/addToCart',UserController.addToCart)
router.post('/wishlist',UserController.wishlist)
router.get('/products/:itemId',UserController.products)
router.get('/reviews/:id',UserController.reviews)
router.post('/addReview',UserController.addReview)
router.get('/userWishlist/:email',UserController.userWishlist)
router.delete('/delWishlist/:productId/:userEmail',UserController.delWishlist)
router.get('/userCart/:email',UserController.userCart)
router.delete('/delCart/:productId/:userEmail',UserController.delCart)
router.post('/orders',UserController.order)
router.get('/userEmail/:_id',UserController.userEmail)
router.get('/user/:email',UserController.user)
router.get('/orderHistory/:email',UserController.orderHistory)
// router.get('/dashboard',UserController.verifyUser)
module.exports=router;